name: goreleaser
on:
  push:
    tags:
    - v*

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22-bullseye

    steps:
      -
        name: Dependencies
        run: apt-get update && apt-get install git -y

      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: git config
        run: git config --global --add safe.directory '*'

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}